image: archlinux
secrets:
- 2630423b-b29c-44d3-813f-5284b32fb8b0
- 455093dd-02f6-485a-b5bb-c7b3491c5725
packages:
  - curl
  # - podman
  - docker
tasks:
  - setup: |
      curl -L https://fly.io/install.sh | sudo env FLYCTL_INSTALL=/usr/local sh
      sudo systemctl start docker.service
      #sudo touch /etc/subuid /etc/subgid
      #sudo usermod --add-subuids 100000-165535 $(whoami)
      #sudo usermod --add-subgids 100000-165535 $(whoami)
  - deploy: |
      #systemctl --user start podman.socket
      #DOCKER_HOST=unix:///run/user/$(id -u)/podman/podman.sock /flyctl deploy podman-daemon
      flyctl deploy podman-daemon
