# fly.toml file generated for podman on 2021-08-18T11:36:28+05:30

app = "podman"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  private_network = true
  allowed_public_ports = []
  auto_rollback = true

[[mounts]]
  destination = "/home/podman/.local/share/containers"
  source = "containers"
